FROM python:3.9-slim
WORKDIR /app
COPY . ./app
RUN pip install flask 
EXPOSE 5000 
# Expose port 5000 for the Flask app
CMD ["python", "app/app.py"]
# Entrypoint command to run the Flask app
# This command will start the Flask application when the container is run